### ISSUE TITLE
MongoDB Example doesnt download

### ISSUE THREAD

**Issue by idkjs** [apollographql/launchpad#10]
to reproduce
1. open <https://launchpad.graphql.com/vkmr1kl83>
2. click fork.
3. add mlab endpoint
3. click download.
4. note error message at bottom. "Error compiling the code. Click to reset to saved version."

**Comment by stubailo** [comment]
Thank you for filing the issue!

**Comment by freiksenet** [comment]
@idkjs I've tried downloading it today, it seems to be working now. I guess we could have accidentally fixed it :) Could you confirm that it works for you?

**Comment by idkjs** [comment]
Works now.
