### ISSUE TITLE
Running Launchpad without Auth0?

### ISSUE THREAD

**Issue by unknown321** [apollographql/launchpad#121]
We would like to host Launchpad entirely on our own servers without running our code on Auth0 servers or using Auth0 as a authentication service. Is it possible?

**Comment by stubailo** [comment]
It's not because the Auth0 service is what manages running the code. Otherwise you'd have to manage spinning containers up and down yourself.

**Comment by unknown321** [comment]
I see. 
Managing containers by myself doesn't seem to be a huge problem: docker swarm + some kind of router redirecting the code to corresponding container. 

Being dependant on Auth0 and not being able to work when it goes down (DDOS, maintenance, power outage, etc.) is not convenient; it also forces us to use Auth0 Extend - that seems unreasonable since we have some servers ready to run some containers.

**Comment by stubailo** [comment]
Sure, I'm just explaining why we used Extend - it was specifically to avoid managing our own containers. Gonna close this issue since the answer is currently no, although you are welcome to send a PR or make a fork that can run on your own infrastructure!
