### ISSUE TITLE
Persistence of secrets in launchpad

### ISSUE THREAD

**Issue by idkjs** [apollographql/launchpad#13]
I went back to check on https://launchpad.graphql.com/k7mmlwwl7 and it was throwing an error saying the secret string was not defined. I then went to check the live instance at https://books-recompose.now.sh/ and it was not rendering data. It was stuck in loading. I then added the connection string back and it worked. Not sure what that was about but thought I would give you a heads up.

**Comment by stubailo** [comment]
Interesting! @freiksenet any thoughts? I haven't come across secrets disappearing before.

**Comment by idkjs** [comment]
I'll let you know if it happens again. Close for now.
