### ISSUE TITLE
Open source Launchpad itself

### ISSUE THREAD

**Issue by idibidiart** [apollographql/launchpad#2]
Wanting to play around with it and maybe use it as part of a bigger project. Is Launchpad itself open sourced?

**Comment by stubailo** [comment]
Not yet! But we probably won't open source the server for a while even if we open source the client part. What are you trying to build?

**Comment by idibidiart** [comment]
It makes GraphQL accessible to more developer the more tools are built for it, like Launchpad. So open sourcing is not important in this case except where there is opportunity to use this work as part of a larger app assembly line, and I'm only working on the UI part of it, but this would be a good compliment, potentially.

Anyway, just thought I get an idea of where you're going with it.

Good tool Sad it only has 31 stars so far. Should be more like 300. Where are all the curious devs? 

From my experience some people get GQL instantly and others never do. It's one of those things, which is why I was arguing to keep it minimalistic (reduce the surface for friction), but that's a different topic.

**Comment by stubailo** [comment]
> Good tool Sad it only has 31 stars so far. Should be more like 300. Where are all the curious devs?

Most people who are using Launchpad aren't on this repo, they just use the UI!

**Comment by m1guelpf** [comment]
Here get a 🌟 . Also, 👍 about making Launchpad open-source 😄

**Comment by idibidiart** [comment]
I can't believe I forgot to star it ... Every star matters! till it's over 10k, then it can go get a job and its own place...

**Comment by stubailo** [comment]
Hah. I think starring the actual code when it's open sourced will be more important! We're all taking a bit of a break after going to a bunch of conferences and launching Launchpad, but hope to get to this next week!

**Comment by idibidiart** [comment]
Great! Closing this now.

**Comment by stubailo** [comment]
I think it's good to have the issue so that we can close it when we're done :]

**Comment by freiksenet** [comment]
Resolved.

**Comment by idibidiart** [comment]
Thank you! you just made my year! :)
