### ISSUE TITLE
CRITICAL: Forked launchpads show only original launchpad's logs

### ISSUE THREAD

**Issue by kbrandwijk** [apollographql/launchpad#76]
I created a launchpad, then I (or someone else!!!) forked that launchpad.

Now in the new forked launchpad, it seems as though console.logs don't work anymore (I get no log output when I run a query). - ERROR 1

Now, accidentally, I ran a query in the original launchpad. And lo and behold, the logs showed up in the _forked_ launchpad's console log. - ERROR 2

This can have very nasty side effects. For example, I logged the request headers in my launchpad, and the one who forked it told me my IP address...

**Comment by wKovacs64** [comment]
I am the "someone else" in this story, in case anyone needs anything from me.

**Comment by kbrandwijk** [comment]
Any update on this?!
