### ISSUE TITLE
Update deprecated dependencies in downloaded project

### ISSUE THREAD

**Issue by kbrandwijk** [apollographql/launchpad#81]
When you download a launchpad, the dependency for `apollo-server-express` specifies version `0.6.0`. Critical fixes, as well as support for tracing and cacheControl, came later. Please keep the dependencies up to date.

**Comment by stubailo** [comment]
#82 got a good start on that!

**Comment by kbrandwijk** [comment]
I actually think this can be closed because #82 is merged.

**Comment by stubailo** [comment]
Great!
