### ISSUE TITLE
Bump apollo-engine

### ISSUE THREAD

**Issue by thepwagner** [apollographql/launchpad#84]
As a launchpad user,
I want to be using the latest version of apollo-engine-js,
So that https://github.com/apollographql/apollo-engine-js/issues/67 is not encountered.

Is this just https://github.com/apollographql/launchpad/blob/72cd8b30468d8bdefeb4f50414bc448b7315b210/server/WebtaskProvider.js#L30 ?

**Comment by evans** [comment]
#96 🎉
