### ISSUE TITLE
It does not display all the pads which I have authored

### ISSUE THREAD

**Issue by indcoder** [apollographql/launchpad#9]
So I created a few different pads and called it a day. When I returned the next day to work on a particular pad and logged in via Auth0, I dont see the pads which I had created under my login, it always start  new launchpad and I cannot retrieve a particular pad if I had not saved the URL somewhere.

Ideally, the login/username menu item should have the facility to  show all the pads that a particular user has authored.

**Comment by stubailo** [comment]
This is something we are working on this week, thanks for the suggestion!

**Comment by freiksenet** [comment]
@indcoder This feature is now done. You can see list of your pads by clicking on your profile. :)

**Comment by indcoder** [comment]
@freiksenet Also I think the pads are listed in order of creation....but this is not made explicit on the page.
