### ISSUE TITLE
Secrets are not available in context function

### ISSUE THREAD

**Issue by ilabacheuski** [apollographql/launchpad#98]
https://launchpad.graphql.com/4r88j8pnn9

It turns out for me and just any new launchpad, that secrets are not really available in `context` function. I think that is something with security that prevents it to be sent as a second parameter. I got `Undefined` or `undefined` instead of right secrets. What is interesting that secrets looks to be set for old projects

**Comment by ilabacheuski** [comment]
It looks like context function is not called at all right now. that is strange. I worry - do I have a glitch or it is a common behavior...
Right now I've tried to console.log inside context function and it does not work. The context in resolver is an empty object.

Tested in chromium v65 incognito mode Linux 4.15

**Comment by evans** [comment]
@ilabacheuski Definitely an issue after #96 too. I'm investigating now

**Comment by evans** [comment]
@ilabacheuski Thanks for flagging the issue! You'll have to refresh the pad with a save and it should work
